services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn test_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9